### PR TITLE
Catch keyboard interrupt

### PR DESCRIPTION
**Pull request by klloe**

### CODE REVIEW

**Comment by x89** [comment]
Can you explain your thoughts behind catching keyboard interrupts? It doesn't seem very import to me, if one tries to kill the process with `^C` then the process will die as expected, as far as I I'm concerned there's not much need for a message telling you that it was successful — that's not standard in most Unix utils!

**Comment by klloe** [comment]
Looks nicer :joy_cat: 

```
DEBUG:shreddit:Examining item 4: dhimwme
DEBUG:shreddit:Item occurs prior to nuke cutoff
^CTraceback (most recent call last):
  File "shreddit/app.py", line 58, in <module>
    main()
  File "shreddit/app.py", line 54, in main
    shredder.shred()
  File "/home/manu/tmp/Shreddit/shreddit/shredder.py", line 68, in shred
    deleted = self._remove_things(self._build_iterator())
  File "/home/manu/tmp/Shreddit/shreddit/shredder.py", line 157, in _remove_things
    self._remove(item)
  File "/home/manu/tmp/Shreddit/shreddit/shredder.py", line 128, in _remove
    self._save_item(item)
  File "/home/manu/tmp/Shreddit/shreddit/shredder.py", line 104, in _save_item
    output["subreddit"] = output["subreddit"].title
  File "/home/manu/tmp/Shreddit/lib/python3.6/site-packages/praw/models/reddit/base.py", line 31, in __getattr__
    self._fetch()
  File "/home/manu/tmp/Shreddit/lib/python3.6/site-packages/praw/models/reddit/base.py", line 64, in _fetch
    other = self._reddit.get(self._info_path())
  File "/home/manu/tmp/Shreddit/lib/python3.6/site-packages/praw/reddit.py", line 322, in get
    data = self.request('GET', path, params=params)
  File "/home/manu/tmp/Shreddit/lib/python3.6/site-packages/praw/reddit.py", line 406, in request
    params=params)
  File "/home/manu/tmp/Shreddit/lib/python3.6/site-packages/prawcore/sessions.py", line 134, in request
    params=params,  url=url)
  File "/home/manu/tmp/Shreddit/lib/python3.6/site-packages/prawcore/sessions.py", line 73, in _request_with_retries
    params=params)
  File "/home/manu/tmp/Shreddit/lib/python3.6/site-packages/prawcore/rate_limit.py", line 27, in call
    self.delay()
  File "/home/manu/tmp/Shreddit/lib/python3.6/site-packages/prawcore/rate_limit.py", line 39, in delay
    time.sleep(sleep_seconds)
KeyboardInterrupt
```

vs

```
DEBUG:shreddit:Examining item 4: dhimwme
DEBUG:shreddit:Item occurs prior to nuke cutoff
^CShreddit aborted by user
```

**Comment by x89** [comment]
Okay point well made, I'll take it. :+1:

**Comment by klloe** [comment]
@x89 awww, you're so kind :kissing_cat:

**Pull request merged**
